In [1]:
import pandas as pd
import numpy as np

from pydataset import data
import os

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

import acquire
import prepare

In [ ]:
import env

In [ ]:
from env import host, user, password

In [ ]:
def get_connection(db, username=user, host=host, password=password):
    return f'mysql+pymysql://{username}:{password}@{host}/{db}'

In [ ]:
def new_telco_data():
    '''
    This function reads the telco data from the Codeup db into a df.
    '''
    sql_query = """
                select * from customers
                join contract_types using (contract_type_id)
                join internet_service_types using (internet_service_type_id)
                join payment_types using (payment_type_id)
                """
    
    # Read in DataFrame from Codeup db.
    df = pd.read_sql(sql_query, get_connection('telco_churn'))
    
    return df

In [ ]:
df= new_telco_data()
df

In [2]:
import acquire

In [3]:
df = acquire.get_telco_data()
df

,payment_type_id,internet_service_type_id,contract_type_id,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,...,tech_support,streaming_tv,streaming_movies,paperless_billing,monthly_charges,total_charges,churn,contract_type,internet_service_type,payment_type
0,2,1,2,0002-ORFBO,Female,0,Yes,Yes,9,Yes,...,Yes,Yes,No,Yes,65.60,593.3,No,One year,DSL,Mailed check
1,2,1,1,0003-MKNFE,Male,0,No,No,9,Yes,...,No,No,Yes,No,59.90,542.4,No,Month-to-month,DSL,Mailed check
2,1,2,1,0004-TLHLJ,Male,0,No,No,4,Yes,...,No,No,No,Yes,73.90,280.85,Yes,Month-to-month,Fiber optic,Electronic check
3,1,2,1,0011-IGKFF,Male,1,Yes,No,13,Yes,...,No,Yes,Yes,Yes,98.00,1237.85,Yes,Month-to-month,Fiber optic,Electronic check
4,2,2,1,0013-EXCHZ,Female,1,Yes,No,3,Yes,...,Yes,Yes,No,Yes,83.90,267.4,Yes,Month-to-month,Fiber optic,Mailed check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2,1,2,9987-LUTYD,Female,0,No,No,13,Yes,...,Yes,No,No,No,55.15,742.9,No,One year,DSL,Mailed check
7039,1,2,1,9992-RRAMN,Male,0,Yes,No,22,Yes,...,No,No,Yes,Yes,85.10,1873.7,Yes,Month-to-month,Fiber optic,Electronic check
7040,2,1,1,9992-UJOEL,Male,0,No,No,2,Yes,...,No,No,No,Yes,50.30,92.75,No,Month-to-month,DSL,Mailed check
7041,2,1,3,9993-LHIEB,Male,0,Yes,Yes,67,Yes,...,Yes,No,Yes,No,67.85,4627.65,No,Two year,DSL,Mailed check
7042,1,1,3,9995-HOTOH,Male,0,Yes,Yes,63,No,...,No,Yes,Yes,No,59.00,3707.6,No,Two year,DSL,Electronic check

In [4]:
import prepare

In [6]:
telco = prepare.prep_telco_data(df)
pd.set_option('display.max_columns', None)
telco.head()

,payment_type_id,internet_service_type_id,contract_type_id,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,paperless_billing,monthly_charges,total_charges,churn,contract_type,internet_service_type,payment_type,gender_encoded,partner_encoded,dependents_encoded,phone_service_encoded,paperless_billing_encoded,churn_encoded,multiple_lines_No phone service,multiple_lines_Yes,online_security_No internet service,online_security_Yes,online_backup_No internet service,online_backup_Yes,device_protection_No internet service,device_protection_Yes,tech_support_No internet service,tech_support_Yes,streaming_tv_No internet service,streaming_tv_Yes,streaming_movies_No internet service,streaming_movies_Yes,contract_type_One year,contract_type_Two year,internet_service_type_Fiber optic,internet_service_type_None,payment_type_Credit card (automatic),payment_type_Electronic check,payment_type_Mailed check
0,2,1,2,0002-ORFBO,Female,0,Yes,Yes,9,Yes,No,No,Yes,No,Yes,Yes,No,Yes,65.6,593.30,No,One year,DSL,Mailed check,1,1,1,1,1,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1
1,2,1,1,0003-MKNFE,Male,0,No,No,9,Yes,Yes,No,No,No,No,No,Yes,No,59.9,542.40,No,Month-to-month,DSL,Mailed check,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
2,1,2,1,0004-TLHLJ,Male,0,No,No,4,Yes,No,No,No,Yes,No,No,No,Yes,73.9,280.85,Yes,Month-to-month,Fiber optic,Electronic check,0,0,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0
3,1,2,1,0011-IGKFF,Male,1,Yes,No,13,Yes,No,No,Yes,Yes,No,Yes,Yes,Yes,98.0,1237.85,Yes,Month-to-month,Fiber optic,Electronic check,0,1,0,1,1,1,0,0,0,0,0,1,0,1,0,0,0,1,0,1,0,0,1,0,0,1,0
4,2,2,1,0013-EXCHZ,Female,1,Yes,No,3,Yes,No,No,No,No,Yes,Yes,No,Yes,83.9,267.40,Yes,Month-to-month,Fiber optic,Mailed check,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,1

In [7]:
telco.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 51 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   payment_type_id                        7032 non-null   int64
 1   internet_service_type_id               7032 non-null   int64
 2   contract_type_id                       7032 non-null   int64
 3   customer_id                            7032 non-null   object
 4   gender                                 7032 non-null   object
 5   senior_citizen                         7032 non-null   int64
 6   partner                                7032 non-null   object
 7   dependents                             7032 non-null   object
 8   tenure                                 7032 non-null   int64
 9   phone_service                          7032 non-null   object
 10  multiple_lines                         7032 non-null   object
 11  online_security                        7032 non-null   object
 12  online_backup                          7032 non-null   object
 13  device_protection                      7032 non-null   object
 14  tech_support                           7032 non-null   object
 15  streaming_tv                           7032 non-null   object
 16  streaming_movies                       7032 non-null   object
 17  paperless_billing                      7032 non-null   object
 18  monthly_charges                        7032 non-null   float64
 19  total_charges                          7032 non-null   float64
 20  churn                                  7032 non-null   object
 21  contract_type                          7032 non-null   object
 22  internet_service_type                  7032 non-null   object
 23  payment_type                           7032 non-null   object
 24  gender_encoded                         7032 non-null   int64
 25  partner_encoded                        7032 non-null   int64
 26  dependents_encoded                     7032 non-null   int64
 27  phone_service_encoded                  7032 non-null   int64
 28  paperless_billing_encoded              7032 non-null   int64
 29  churn_encoded                          7032 non-null   int64
 30  multiple_lines_No phone service        7032 non-null   uint8
 31  multiple_lines_Yes                     7032 non-null   uint8
 32  online_security_No internet service    7032 non-null   uint8
 33  online_security_Yes                    7032 non-null   uint8
 34  online_backup_No internet service      7032 non-null   uint8
 35  online_backup_Yes                      7032 non-null   uint8
 36  device_protection_No internet service  7032 non-null   uint8
 37  device_protection_Yes                  7032 non-null   uint8
 38  tech_support_No internet service       7032 non-null   uint8
 39  tech_support_Yes                       7032 non-null   uint8
 40  streaming_tv_No internet service       7032 non-null   uint8
 41  streaming_tv_Yes                       7032 non-null   uint8
 42  streaming_movies_No internet service   7032 non-null   uint8
 43  streaming_movies_Yes                   7032 non-null   uint8
 44  contract_type_One year                 7032 non-null   uint8
 45  contract_type_Two year                 7032 non-null   uint8
 46  internet_service_type_Fiber optic      7032 non-null   uint8
 47  internet_service_type_None             7032 non-null   uint8
 48  payment_type_Credit card (automatic)   7032 non-null   uint8
 49  payment_type_Electronic check          7032 non-null   uint8
 50  payment_type_Mailed check              7032 non-null   uint8
dtypes: float64(2), int64(11), object(17), uint8(21)
memory usage: 1.8+ MB